### ISSUE TITLE
Create sample EPUB with page images

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#872]
This card serves two purposes:
- Test performance in cozy sun bear
- Evaluate UX for reading such an EPUB.

- [x] Assemble a valid EPUB 3.1 file in which all content is page images.

**Comment by jgmorse** [comment]
Once upon a time, Amanda Karby was going to do this.  I will check with MPS to see if there are any cycles available to do this.

**Comment by sethaj** [comment]
The PR attached to this was meant for #873. Oops. Just ignore it, there won't be a PR for this story anyway...

**Comment by jgmorse** [comment]
Patrick Goussy of MPS is doing this.

**Comment by jmcglone** [comment]
fixed epub: continually fails in resque and in some cases doesn't kick-off a job
manga 2: https://heliotrope-staging.hydra.lib.umich.edu/epub/qz20ss75n
manga 3: https://heliotrope-staging.hydra.lib.umich.edu/epub/s1784k96q
manga 4: https://heliotrope-staging.hydra.lib.umich.edu/epub/n009w248z

because each page is set to a chapter the following issues are noticed immediately:

there is no 2-up view (two pages at once)
because we are serving a chapter at a time, images that are larger take a while to load, and it isn't immediately clear the page is loading
the metadata is pretty insufficient

**Comment by jmcglone** [comment]
Also, the < > navigation is really weird. sometimes pages load, sometimes they don't leaving one confused where they actually are in the epub. very strange.

**Comment by jmcglone** [comment]
Seems like Magna 2 is only one who's performance is acceptable (and it is the lowest quality file at 1.8MB)

**Comment by respinos** [comment]
The manga epubs are missing the necessary properties to function as a pre-paginated book; they're defaulting to reflowable.

fixed epub is closer, but the viewport dimensions need to be the same as the image dimensions.

**Comment by jgmorse** [comment]
I'll check against my own checklist for requirements of fixed-position epubs.

**Comment by jgmorse** [comment]
Sample file is here:
https://drive.google.com/open?id=0B-18ovAEQgwvYXVoc3hYTmxRcjQ

It's working in both CozySunBear and iBooks. Page images are reduced to 640x1010 pixels for better performance.

http://validator.idpf.org/ is yielding one error which I still don't understand:
"ERROR	EPUB/Navigation/nav.xhtml	Line 6	Position 11	Fixed format item has no viewport defined."  (There is no fixed format item defined on that line or above it....)
